// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class __locale_struct {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(13, C_POINTER).withName("__locales"),
        C_POINTER.withName("__ctype_b"),
        C_POINTER.withName("__ctype_tolower"),
        C_POINTER.withName("__ctype_toupper"),
        MemoryLayout.sequenceLayout(13, C_POINTER).withName("__names")
    ).withName("__locale_struct");
    public static MemoryLayout $LAYOUT() {
        return __locale_struct.$struct$LAYOUT;
    }
    public static MemorySegment __locales$slice(MemorySegment seg) {
        return seg.asSlice(0, 104);
    }
    static final VarHandle __ctype_b$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__ctype_b")));
    public static VarHandle __ctype_b$VH() {
        return __locale_struct.__ctype_b$VH;
    }
    public static MemoryAddress __ctype_b$get(MemorySegment seg) {
        return (MemoryAddress)__locale_struct.__ctype_b$VH.get(seg);
    }
    public static void __ctype_b$set( MemorySegment seg, MemoryAddress x) {
        __locale_struct.__ctype_b$VH.set(seg, x);
    }
    public static MemoryAddress __ctype_b$get(MemorySegment seg, long index) {
        return (MemoryAddress)__locale_struct.__ctype_b$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __ctype_b$set(MemorySegment seg, long index, MemoryAddress x) {
        __locale_struct.__ctype_b$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __ctype_tolower$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__ctype_tolower")));
    public static VarHandle __ctype_tolower$VH() {
        return __locale_struct.__ctype_tolower$VH;
    }
    public static MemoryAddress __ctype_tolower$get(MemorySegment seg) {
        return (MemoryAddress)__locale_struct.__ctype_tolower$VH.get(seg);
    }
    public static void __ctype_tolower$set( MemorySegment seg, MemoryAddress x) {
        __locale_struct.__ctype_tolower$VH.set(seg, x);
    }
    public static MemoryAddress __ctype_tolower$get(MemorySegment seg, long index) {
        return (MemoryAddress)__locale_struct.__ctype_tolower$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __ctype_tolower$set(MemorySegment seg, long index, MemoryAddress x) {
        __locale_struct.__ctype_tolower$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __ctype_toupper$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__ctype_toupper")));
    public static VarHandle __ctype_toupper$VH() {
        return __locale_struct.__ctype_toupper$VH;
    }
    public static MemoryAddress __ctype_toupper$get(MemorySegment seg) {
        return (MemoryAddress)__locale_struct.__ctype_toupper$VH.get(seg);
    }
    public static void __ctype_toupper$set( MemorySegment seg, MemoryAddress x) {
        __locale_struct.__ctype_toupper$VH.set(seg, x);
    }
    public static MemoryAddress __ctype_toupper$get(MemorySegment seg, long index) {
        return (MemoryAddress)__locale_struct.__ctype_toupper$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __ctype_toupper$set(MemorySegment seg, long index, MemoryAddress x) {
        __locale_struct.__ctype_toupper$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment __names$slice(MemorySegment seg) {
        return seg.asSlice(128, 104);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


