// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$4 {

    static final FunctionDescriptor fuse_version$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle fuse_version$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_version",
        "()I",
        constants$4.fuse_version$FUNC, false
    );
    static final FunctionDescriptor fuse_pkgversion$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle fuse_pkgversion$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_pkgversion",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$4.fuse_pkgversion$FUNC, false
    );
    static final FunctionDescriptor fuse_pollhandle_destroy$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle fuse_pollhandle_destroy$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_pollhandle_destroy",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$4.fuse_pollhandle_destroy$FUNC, false
    );
    static final FunctionDescriptor fuse_buf_size$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle fuse_buf_size$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_buf_size",
        "(Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$4.fuse_buf_size$FUNC, false
    );
    static final FunctionDescriptor fuse_buf_copy$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fuse_buf_copy$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_buf_copy",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)J",
        constants$4.fuse_buf_copy$FUNC, false
    );
    static final FunctionDescriptor fuse_set_signal_handlers$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fuse_set_signal_handlers$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_set_signal_handlers",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$4.fuse_set_signal_handlers$FUNC, false
    );
}


