// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$0 {

    static final FunctionDescriptor fuse_opt_proc_t$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fuse_opt_proc_t$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fuse_opt_proc_t$FUNC, false
    );
    static final FunctionDescriptor fuse_opt_parse$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_opt_parse$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_parse",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fuse_opt_parse$FUNC, false
    );
    static final FunctionDescriptor fuse_opt_add_opt$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_opt_add_opt$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_add_opt",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fuse_opt_add_opt$FUNC, false
    );
    static final FunctionDescriptor fuse_opt_add_opt_escaped$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_opt_add_opt_escaped$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_add_opt_escaped",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fuse_opt_add_opt_escaped$FUNC, false
    );
    static final FunctionDescriptor fuse_opt_add_arg$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_opt_add_arg$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_add_arg",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fuse_opt_add_arg$FUNC, false
    );
}


