// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1 {

    static final FunctionDescriptor fuse_opt_insert_arg$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fuse_opt_insert_arg$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_insert_arg",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$1.fuse_opt_insert_arg$FUNC, false
    );
    static final FunctionDescriptor fuse_opt_free_args$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle fuse_opt_free_args$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_free_args",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.fuse_opt_free_args$FUNC, false
    );
    static final FunctionDescriptor fuse_opt_match$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_opt_match$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_opt_match",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1.fuse_opt_match$FUNC, false
    );
    static final FunctionDescriptor fuse_log_func_t$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_log_func_t$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.fuse_log_func_t$FUNC, false
    );
    static final FunctionDescriptor fuse_set_log_func$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle fuse_set_log_func$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_set_log_func",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.fuse_set_log_func$FUNC, false
    );
}


