// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$13 {

    static final FunctionDescriptor chmod$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle chmod$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "chmod",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$13.chmod$FUNC, false
    );
    static final FunctionDescriptor lchmod$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle lchmod$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "lchmod",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$13.lchmod$FUNC, false
    );
    static final FunctionDescriptor fchmod$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle fchmod$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fchmod",
        "(II)I",
        constants$13.fchmod$FUNC, false
    );
    static final FunctionDescriptor fchmodat$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fchmodat$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fchmodat",
        "(ILjdk/incubator/foreign/MemoryAddress;II)I",
        constants$13.fchmodat$FUNC, false
    );
    static final FunctionDescriptor umask$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle umask$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "umask",
        "(I)I",
        constants$13.umask$FUNC, false
    );
    static final FunctionDescriptor mkdir$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle mkdir$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "mkdir",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$13.mkdir$FUNC, false
    );
}


