// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$19 {

    static final FunctionDescriptor fuse_clean_cache$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fuse_clean_cache$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_clean_cache",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fuse_clean_cache$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_getattr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_fs_getattr$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_getattr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fuse_fs_getattr$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_rename$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fuse_fs_rename$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_rename",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$19.fuse_fs_rename$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_unlink$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_fs_unlink$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_unlink",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fuse_fs_unlink$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_rmdir$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_fs_rmdir$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_rmdir",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fuse_fs_rmdir$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_symlink$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_fs_symlink$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_symlink",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fuse_fs_symlink$FUNC, false
    );
}


