// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$8 {

    static final FunctionDescriptor asctime$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle asctime$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "asctime",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$8.asctime$FUNC, false
    );
    static final FunctionDescriptor ctime$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle ctime$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "ctime",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$8.ctime$FUNC, false
    );
    static final FunctionDescriptor asctime_r$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle asctime_r$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "asctime_r",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$8.asctime_r$FUNC, false
    );
    static final FunctionDescriptor ctime_r$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle ctime_r$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "ctime_r",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$8.ctime_r$FUNC, false
    );
    static final MemoryLayout __tzname$LAYOUT = MemoryLayout.sequenceLayout(2, C_POINTER);
    static final MemorySegment __tzname$SEGMENT = RuntimeHelper.lookupGlobalVariable(fuse_h.LIBRARIES, "__tzname", constants$8.__tzname$LAYOUT);
    static final MemoryLayout __daylight$LAYOUT = C_INT;
    static final VarHandle __daylight$VH = constants$8.__daylight$LAYOUT.varHandle(int.class);
    static final MemorySegment __daylight$SEGMENT = RuntimeHelper.lookupGlobalVariable(fuse_h.LIBRARIES, "__daylight", constants$8.__daylight$LAYOUT);
}


