// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$23 {

    static final FunctionDescriptor fuse_fs_chown$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fuse_fs_chown$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_chown",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;)I",
        constants$23.fuse_fs_chown$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_truncate$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle fuse_fs_truncate$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_truncate",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I",
        constants$23.fuse_fs_truncate$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_utimens$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_fs_utimens$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_utimens",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$23.fuse_fs_utimens$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_access$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fuse_fs_access$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_access",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$23.fuse_fs_access$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_readlink$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle fuse_fs_readlink$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_readlink",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$23.fuse_fs_readlink$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_mknod$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_LONG
    );
    static final MethodHandle fuse_fs_mknod$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_mknod",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$23.fuse_fs_mknod$FUNC, false
    );
}


