// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$27 {

    static final FunctionDescriptor fuse_open_channel$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_open_channel$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_open_channel",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$27.fuse_open_channel$FUNC, false
    );
    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
}


