// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$2 {

    static final FunctionDescriptor fuse_log$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle fuse_log$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_log",
        "(ILjdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)V",
        constants$2.fuse_log$FUNC, true
    );
    static final FunctionDescriptor __bswap_16$FUNC = FunctionDescriptor.of(C_SHORT,
        C_SHORT
    );
    static final MethodHandle __bswap_16$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "__bswap_16",
        "(S)S",
        constants$2.__bswap_16$FUNC, false
    );
    static final FunctionDescriptor __bswap_32$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle __bswap_32$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "__bswap_32",
        "(I)I",
        constants$2.__bswap_32$FUNC, false
    );
    static final FunctionDescriptor __bswap_64$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG
    );
    static final MethodHandle __bswap_64$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "__bswap_64",
        "(J)J",
        constants$2.__bswap_64$FUNC, false
    );
    static final FunctionDescriptor __uint16_identity$FUNC = FunctionDescriptor.of(C_SHORT,
        C_SHORT
    );
    static final MethodHandle __uint16_identity$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "__uint16_identity",
        "(S)S",
        constants$2.__uint16_identity$FUNC, false
    );
    static final FunctionDescriptor __uint32_identity$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle __uint32_identity$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "__uint32_identity",
        "(I)I",
        constants$2.__uint32_identity$FUNC, false
    );
}


