// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$24 {

    static final FunctionDescriptor fuse_fs_mkdir$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fuse_fs_mkdir$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_mkdir",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$24.fuse_fs_mkdir$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_setxattr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_INT
    );
    static final MethodHandle fuse_fs_setxattr$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_setxattr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JI)I",
        constants$24.fuse_fs_setxattr$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_getxattr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle fuse_fs_getxattr$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_getxattr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$24.fuse_fs_getxattr$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_listxattr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle fuse_fs_listxattr$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_listxattr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$24.fuse_fs_listxattr$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_removexattr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fuse_fs_removexattr$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_removexattr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$24.fuse_fs_removexattr$FUNC, false
    );
    static final FunctionDescriptor fuse_fs_bmap$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle fuse_fs_bmap$MH = RuntimeHelper.downcallHandle(
        fuse_h.LIBRARIES, "fuse_fs_bmap",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I",
        constants$24.fuse_fs_bmap$FUNC, false
    );
}


