// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class fuse_opt {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_POINTER.withName("templ"),
        C_LONG.withName("offset"),
        C_INT.withName("value"),
        MemoryLayout.paddingLayout(32)
    ).withName("fuse_opt");
    public static MemoryLayout $LAYOUT() {
        return fuse_opt.$struct$LAYOUT;
    }
    static final VarHandle templ$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("templ")));
    public static VarHandle templ$VH() {
        return fuse_opt.templ$VH;
    }
    public static MemoryAddress templ$get(MemorySegment seg) {
        return (MemoryAddress)fuse_opt.templ$VH.get(seg);
    }
    public static void templ$set( MemorySegment seg, MemoryAddress x) {
        fuse_opt.templ$VH.set(seg, x);
    }
    public static MemoryAddress templ$get(MemorySegment seg, long index) {
        return (MemoryAddress)fuse_opt.templ$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void templ$set(MemorySegment seg, long index, MemoryAddress x) {
        fuse_opt.templ$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle offset$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("offset"));
    public static VarHandle offset$VH() {
        return fuse_opt.offset$VH;
    }
    public static long offset$get(MemorySegment seg) {
        return (long)fuse_opt.offset$VH.get(seg);
    }
    public static void offset$set( MemorySegment seg, long x) {
        fuse_opt.offset$VH.set(seg, x);
    }
    public static long offset$get(MemorySegment seg, long index) {
        return (long)fuse_opt.offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void offset$set(MemorySegment seg, long index, long x) {
        fuse_opt.offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle value$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("value"));
    public static VarHandle value$VH() {
        return fuse_opt.value$VH;
    }
    public static int value$get(MemorySegment seg) {
        return (int)fuse_opt.value$VH.get(seg);
    }
    public static void value$set( MemorySegment seg, int x) {
        fuse_opt.value$VH.set(seg, x);
    }
    public static int value$get(MemorySegment seg, long index) {
        return (int)fuse_opt.value$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void value$set(MemorySegment seg, long index, int x) {
        fuse_opt.value$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


