// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface fuse_opt_proc_t {

    int apply(MemoryAddress x0, MemoryAddress x1, int x2, MemoryAddress x3);
    static MemoryAddress allocate(fuse_opt_proc_t fi) {
        return RuntimeHelper.upcallStub(fuse_opt_proc_t.class, fi, constants$0.fuse_opt_proc_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I");
    }
    static MemoryAddress allocate(fuse_opt_proc_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(fuse_opt_proc_t.class, fi, constants$0.fuse_opt_proc_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static fuse_opt_proc_t ofAddress(MemoryAddress addr) {
        return (MemoryAddress x0, MemoryAddress x1, int x2, MemoryAddress x3) -> {
            try {
                return (int)constants$0.fuse_opt_proc_t$MH.invokeExact((Addressable)addr, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


