// Generated by jextract

package org.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface fuse_log_func_t {

    void apply(int x0, MemoryAddress x1, MemoryAddress x2);
    static MemoryAddress allocate(fuse_log_func_t fi) {
        return RuntimeHelper.upcallStub(fuse_log_func_t.class, fi, constants$1.fuse_log_func_t$FUNC, "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(fuse_log_func_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(fuse_log_func_t.class, fi, constants$1.fuse_log_func_t$FUNC, "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static fuse_log_func_t ofAddress(MemoryAddress addr) {
        return (int x0, MemoryAddress x1, MemoryAddress x2) -> {
            try {
                constants$1.fuse_log_func_t$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


